name: Build and Deploy LaTeX PDF

on:
  push:
    branches:
      - main

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install TeX Live (including XeLaTeX)
        run: |
          sudo apt-get install -y \
            texlive-xetex \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-lang-chinese  # 如果需要中文支持

  compile-pdf:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Compile with XeLaTeX
        run: |
          xelatex main.tex
          # 如果需要多次编译生成正确目录、索引等，可以重复执行 xelatex。
          # xelatex main.tex
          # xelatex main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: Compiled-PDF
          path: main.pdf

  deploy:
    needs: compile-pdf
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: Compiled-PDF

      - name: Create a directory for GH Pages
        run: |
          mkdir -p public
          mv main.pdf public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          # cname: example.com
