name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  # ----------------------------
  # 1) 安装依赖
  # ----------------------------
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install TeX Live (including XeLaTeX)
        run: |
          sudo apt-get install -y \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-lang-chinese  # 如果需要中文支持，可以加上

  # ----------------------------
  # 2) 编译 PDF
  # ----------------------------
  compile-pdf:
    # 只有依赖安装完后，才能编译
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Compile with XeLaTeX
        run: |
          xelatex main.tex
          # 如果需要多次编译生成正确目录、索引等，可以多次调用 xelatex：
          # xelatex main.tex
          # xelatex main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: main.pdf  # 若你的 PDF 命名或路径不同，请改这里

  # ----------------------------
  # 3) 部署到 gh-pages 分支
  # ----------------------------
  deploy:
    # 只有编译完成后才能部署
    needs: compile-pdf
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-pdf

      - name: Prepare public folder
        run: |
          mkdir -p public
          mv main.pdf public/

      # 使用第三方 action 来发布到 gh-pages 分支
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # 指定要部署的分支
