name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install TeX Live (including XeLaTeX)
        run: |
          sudo apt-get install -y \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-lang-chinese  # 若需要中文支持，可加上

      - name: Install siunitx package
        run: sudo apt -y install texlive-science

      - name: Compile with XeLaTeX
        run: |
          xelatex main.tex
          # 若需要多次编译以生成目录、引用等信息，请重复调用 xelatex：
          # xelatex main.tex
          # xelatex main.tex

      - name: Prepare public folder
        run: |
          mkdir -p public
          mv main.pdf public/
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
