name: Build and Deploy LaTeX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up TeX Live
      uses: dante-ev/texlive-action@v2

    - name: Compile LaTeX document
      run: |
        latexmk -pdf -interaction=nonstopmode -output-directory=output main.tex

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
