name: Build and Deploy LaTeX

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:  # Allow manual triggering

jobs:
  install-texlive:
    name: Install TeX Live and latexmk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install TeX Live and latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk

      - name: Verify latexmk installation
        run: |
          which latexmk || echo "latexmk not found"
          latexmk --version || echo "latexmk version could not be fetched"

  create-output-dir:
    name: Create Output Directory
    runs-on: ubuntu-latest
    needs: install-texlive  # Ensure TeX Live is installed first

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p output

  compile-latex:
    name: Compile LaTeX Document
    runs-on: ubuntu-latest
    needs: [install-texlive, create-output-dir]  # Compile only after texlive is installed and output dir exists

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: |
          latexmk -pdf -interaction=nonstopmode -output-directory=output main.tex

  upload-pdf:
    name: Upload Compiled PDF
    runs-on: ubuntu-latest
    needs: compile-latex  # Wait for LaTeX compilation to complete

    steps:
      - name: Upload compiled PDF
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: output/*.pdf

  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: compile-latex  # Ensure LaTeX compilation is finished

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          force_orphan: true
