name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install TeX Live (including XeLaTeX and latexmk)
        run: |
          sudo apt-get install -y \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-extra \
            texlive-lang-chinese \
            latexmk

      - name: Install siunitx package
        run: sudo apt -y install texlive-science

      - name: Compile with latexmk (XeLaTeX)
        run: |
          latexmk -xelatex -synctex=1 -interaction=nonstopmode main.tex

      - name: Prepare public folder and copy all files
        run: |
          mkdir -p public
          cp -r * public/

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
